# This is a basic workflow to help you get started with Actions

name: kernel-aster
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: hapakaien/archlinux-package-action@v2
        with:
          flags: '-s --noconfirm'
          namcap: false
          aur: true
      - name: Run a one-line script
        run: echo Hello, world!
