# This is a basic workflow to help you get started with Actions

name: kernel-aster
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
         pwd
         sudo apt install tar wget
         mkdir ~/kernelbuild
         cd ~/kernelbuild
         wget https://github.com/zen-kernel/zen-kernel/archive/refs/tags/v6.1.7-lqx2.tar.gz
         tar -xf v6.1.7-lqx2.tar.gz
         cd zen-kernel-6.1.7-lqx2
         make mrproper
         cp ~/config .
         make -j4
         make modules
         

         
         
         
