# This is a basic workflow to help you get started with Actions

name: kernel-aster
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Archlinux
        run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
      - name: Docker hello-world
        run: |
          sudo pacman --noconfirm -Syu docker
          sudo systemctl start docker
          docker run --rm hello-world

      - name: Run a one-line script
        run: echo Hello, world!
