# This is a basic workflow to help you get started with Actions

name: kernel-aster
on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 2 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: bash build.sh
             
      - name: Commit report
        run: |
          git add .
          git config --global user.name 'asterlinux'
          git config --global user.email 'asterlinux@users.noreply.github.com'
          git commit -am "Automated report"
          git push
        
             

         
         
         
