# This is a basic workflow to help you get started with Actions

name: kernel-aster
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
         pwd
         ls
         sudo apt install tar wget
         mkdir ~/kernelbuild
         cd ~/kernelbuild
         wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.7.tar.xz
         tar -xf linux-6.1.7.tar.xz
         sudo chown -R $USER:$USER linux-6.1.7
         cd linux-6.1.7
         make mrproper
         cp /home/runner/work/kernel-aster/kernel-aster/config .config
         make -j4
         make modules
         

         
         
         
