# This is a basic workflow to help you get started with Actions

name: kernel_build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt install -y gcc make
      - name: make kernel
        run: make defconfig && make -j "nproc"
