# This is a basic workflow to help you get started with Actions

name: kernel_build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt install -y gcc make git
      - name: download kernel build
        run: |
         git clone https://github.com/zen-kernel/zen-kernel.git
         cd zen-kernel
        
      - name: make kernel
        run: make defconfig && make -j "nproc"
